---
- name: Install cloud-init package
  ansible.builtin.apt:
    name: cloud-init
    state: present
    update_cache: true

- name: Prepare cloud-init
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg
    - /etc/cloud/cloud.cfg.d/99-installer.cfg
    - /etc/netplan/00-installer-config.yaml

- name: Prepare Debian cloud.cfg
  ansible.builtin.copy:
    src: debian-cloud.cfg
    dest: /etc/cloud/cloud.cfg
  when: ansible_distribution == "Debian"

- name: Write Proxmox cloud-init datasource config
  ansible.builtin.copy:
    dest: /etc/cloud/cloud.cfg.d/90_dpkg.cfg
    content: 'datasource_list: [ConfigDrive, NoCloud]'
  when: ansible_facts['virtualization_type'] == "kvm"

- name: Configure VMware
  when: ansible_facts['virtualization_type'] == "VMware"
  block:
    - name: Write vSphere cloud-init datasource config
      ansible.builtin.copy:
        dest: /etc/cloud/cloud.cfg.d/90_dpkg.cfg
        content: 'datasource_list: [ VMware, OVF, None ]'

    - name: Enable VMware customizations
      ansible.builtin.blockinfile:
        path: /etc/cloud/cloud.cfg
        block: |
          disable_vmware_customization: false
          datasource:
            VMware:
              vmware_cust_file_max_wait: 5

    - name: Enable VMware customization scripts
      ansible.builtin.shell: vmware-toolbox-cmd config set deployPkg enable-custom-scripts true
